// Haiku Scientific Calculator
// Bryan DeGrendel (c) 2015
//
// See LICENSE for licensing information.

#ifndef ___ACTION_H___
#define ___ACTION_H___

#include <InterfaceKit.h>

enum ACTION_ID
{
  ACTION_GO,

  ACTION_0, ACTION_1, ACTION_2, ACTION_3, ACTION_4, ACTION_5, ACTION_6,
  ACTION_7, ACTION_8, ACTION_9, ACTION_DECIMAL, ACTION_NEGATION,
  ACTION_SCIENTIFIC_NOTATION,

  ACTION_DELETE, ACTION_CLEAR, ACTION_LEFT, ACTION_UP, ACTION_RIGHT,
  ACTION_DOWN,

  ACTION_PREVIOUS_ANSWER, ACTION_OPEN_PARANESIS,
  ACTION_CLOSE_PARATHENESIS, ACTION_PI,

  ACTION_PLUS, ACTION_MINUS, ACTION_DIVISION, ACTION_MULITPLICATION,

  ACTION_SQUARED, ACTION_POWER_OF, ACTION_SQUARE_ROOT, ACTION_NTH_ROOT,
  ACTION_INVERSE,

  ACTION_SINE, ACTION_COSINE, ACTION_TANGENT, ACTION_ARCSINE,
  ACTION_ARCCOSINE, ACTION_ARCTANGENT,
  ACTION_LOG, ACTION_TEN_POWER, ACTION_NATURAL_LOG, ACTION_E_POWER,

  ACTION_LAST_ELEMENT
};


class Action : public BButton
{
public:
  Action(const char *name, ACTION_ID id);

private:
  ACTION_ID id;
};

#endif // ___ACTION_H___

